




/*-------- emitter --------*/

export const EMITTER_ACTION_REQUEST = 'EMITTER_ACTION_REQUEST';

export const EMITTER_ACTION_SIGN = 'EMITTER_ACTION_SIGN';

export const EMITTER_ACTION_JOIN = 'EMITTER_ACTION_JOIN';
export const EMITTER_ACTION_LEAVE = 'EMITTER_ACTION_LEAVE';
export const EMITTER_ACTION_JOIN_ALL = 'EMITTER_ACTION_JOIN_ALL';
export const EMITTER_ACTION_LEAVE_ALL = 'EMITTER_ACTION_LEAVE_ALL';

export const EMITTER_ACTION_DELIVER_MESSAGE = 'EMITTER_ACTION_DELIVER_MESSAGE';
export const EMITTER_ACTION_QUERY_MESSAGES = 'EMITTER_ACTION_QUERY_MESSAGES';

export const EMITTER_ACTION_QUERY_CHATS = 'EMITTER_ACTION_QUERY_CHATS';
export const EMITTER_ACTION_QUERY_SCENE = 'EMITTER_ACTION_QUERY_SCENE';
export const EMITTER_ACTION_MANUAL = 'EMITTER_ACTION_MANUAL';

/*-------- user --------*/

export const USER_SETTER = 'USER_SETTER';
export const USER_ACTION_LOGIN = 'USER_ACTION_LOGIN';
export const USER_ACTION_LOGOUT = 'USER_ACTION_LOGOUT';

/*-------- chat --------*/

export const CHAT_SET_ALIVE = 'CHAT_SET_ALIVE';
export const CHAT_RESET_UNREAD = 'CHAT_RESET_UNREAD';
export const CHAT_INIT_MENU = 'CHAT_INIT_MENU';
export const CHAT_ADD_INFO = 'CHAT_ADD_INFO';
export const CHAT_DELETE = 'CHAT_DELETE';
export const CHAT_CHANGE_ALIVE_BOT = 'CHAT_CHANGE_ALIVE_BOT';
export const CHAT_COMMIT_MESSAGE = 'CHAT_COMMIT_MESSAGE';
export const CHAT_MERGE_MESSAGES = 'CHAT_MERGE_MESSAGES';

export const CHAT_ACTION_MESSAGES_MERGE = 'CHAT_ACTION_MESSAGES_MERGE';
export const CHAT_ACTION_INFO_MERGE = 'CHAT_ACTION_INFO_MERGE';
/*-------- layout --------*/

export const LAYOUT_LOADING_TOGGLE = 'LAYOUT_LOADING_TOGGLE';
export const LAYOUT_DRAWER_TOGGLE = 'LAYOUT_DRAWER_TOGGLE';
export const LAYOUT_SNACK_BAR_TOGGLE = 'LAYOUT_SNACK_BAR_TOGGLE';
export const LAYOUT_MENU_TOGGLE = 'LAYOUT_MENU_TOGGLE';

/*-------- bili --------*/

export const BILI_TOGGLE = 'BILI_TOGGLE';
export const BILI_PLAY = 'BILI_PLAY';











// 全局

// export const SET_ERROR = 'SET_ERROR';
// export const INIT_MENU = 'INIT_MENU';


// layout
// export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
// export const VIDEO_PLAY_SETTER = 'VIDEO_PLAY_SETTER';
// export const PLAY_VIDEO = 'PLAY_VIDEO';
// export const CHAT_TO_BOTTOM = 'CHAT_TO_BOTTOM';
// export const DRAWER_SETTER = 'DRAWER_SETTER';


// loading
// export const LOADING_SETTER = 'LOADING_SETTER';

// chat 相关.
// export const CHAT_ALIVE_SETTER = 'CHAT_ALIVE_SETTER';
// export const CHAT_DELETE = 'CHAT_DELETE';
// export const CHAT_COMMIT_MESSAGE = 'CHAT_COMMIT_MESSAGE';
//
// export const ACTION_LOGIN_USER = 'ACTION_LOGIN_USER';
// export const ACTION_CHAT_CONNECT = 'ACTION_CHAT_CONNECT';
// export const ACTION_CHAT_CLOSE = 'ACTION_CHAT_CLOSE';
// export const ACTION_CHAT_SUBSCRIBE = 'ACTION_CHAT_SUBSCRIBE';
// export const ACTION_CHAT_DISCONNECT = 'ACTION_CHAT_DISCONNECT';

// messages
// export const MESSAGE_TEXT = 'text';
// export const MESSAGE_BILI = 'bili';
// export const MESSAGE_EVENT = 'event';

// user
// export const USER_SETTER = 'USER_SETTER';
// export const ACTION_USER_LOGOUT = 'ACTION_USER_LOGOUT';

// socket
// export const SOCKET_ACTION_MESSAGE = 'SOCKET_ACTION_MESSAGE';
