
export const STORE_ACTION_RESET_ALL = 'STORE_ACTION_RESET_ALL';

/*-------- emitter --------*/

export const EMITTER_ACTION_REQUEST = 'EMITTER_ACTION_REQUEST';

export const EMITTER_ACTION_SIGN = 'EMITTER_ACTION_SIGN';
export const EMITTER_ACTION_REGISTER = 'EMITTER_ACTION_REGISTER';

export const EMITTER_ACTION_JOIN = 'EMITTER_ACTION_JOIN';
export const EMITTER_ACTION_LEAVE = 'EMITTER_ACTION_LEAVE';
export const EMITTER_ACTION_JOIN_ALL = 'EMITTER_ACTION_JOIN_ALL';
export const EMITTER_ACTION_USER_LOGOUT = 'EMITTER_ACTION_USER_LOGOUT';
export const EMITTER_ACTION_LEAVE_ALL = 'EMITTER_ACTION_LEAVE_ALL';

export const EMITTER_ACTION_DELIVER_MESSAGE = 'EMITTER_ACTION_DELIVER_MESSAGE';
export const EMITTER_ACTION_QUERY_MESSAGES = 'EMITTER_ACTION_QUERY_MESSAGES';

export const EMITTER_ACTION_QUERY_CHATS = 'EMITTER_ACTION_QUERY_CHATS';
export const EMITTER_ACTION_QUERY_SCENE = 'EMITTER_ACTION_QUERY_SCENE';
export const EMITTER_ACTION_MANUAL = 'EMITTER_ACTION_MANUAL';

/*-------- user --------*/

export const USER_SETTER = 'USER_SETTER';
export const USER_ACTION_LOGIN = 'USER_ACTION_LOGIN';
export const USER_ACTION_LOGOUT = 'USER_ACTION_LOGOUT';
export const USER_RESET = 'USER_RESET';

/*-------- chat --------*/

export const CHAT_RESET = 'CHAT_RESET';
export const CHAT_ACTION_CONNECT_INCOMING = 'CHAT_ACTION_CONNECT_INCOMING';
export const CHAT_RESET_UNREAD = 'CHAT_RESET_UNREAD';
export const CHAT_INIT_MENU = 'CHAT_INIT_MENU';
export const CHAT_ADD_INFO = 'CHAT_ADD_INFO';
export const CHAT_DELETE = 'CHAT_DELETE';
export const CHAT_TOGGLE_MANUAL = 'CHAT_TOGGLE_MANUAL';
export const CHAT_COMMIT_MESSAGE = 'CHAT_COMMIT_MESSAGE';
export const CHAT_MERGE_MESSAGES = 'CHAT_MERGE_MESSAGES';
export const CHAT_CACHE_CONNECTED = 'CHAT_CACHE_CONNECTED';

export const CHAT_ACTION_TOGGLE_MANUAL = 'CHAT_ACTION_TOGGLE_MANUAL';
export const CHAT_ACTION_MESSAGES_MERGE = 'CHAT_ACTION_MESSAGES_MERGE';
export const CHAT_ACTION_INFO_MERGE = 'CHAT_ACTION_INFO_MERGE';
export const CHAT_ACTION_CLOSE = 'CHAT_ACTION_CLOSE';


/*-------- layout --------*/

export const LAYOUT_LOADING_TOGGLE = 'LAYOUT_LOADING_TOGGLE';
export const LAYOUT_DRAWER_TOGGLE = 'LAYOUT_DRAWER_TOGGLE';
export const LAYOUT_SNACK_BAR_TOGGLE = 'LAYOUT_SNACK_BAR_TOGGLE';
export const LAYOUT_MENU_TOGGLE = 'LAYOUT_MENU_TOGGLE';
export const LAYOUT_RESET = 'LAYOUT_RESET';

/*-------- bili --------*/

export const BILI_RESET = 'BILI_RESET';
export const BILI_TOGGLE = 'BILI_TOGGLE';
export const BILI_PLAY = 'BILI_PLAY';

